spring:
  application:
    name: ticket-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3307/micro
    username: root
    password: 12345678
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
  rabbitmq:
    username: root
    password: 12345678
  cloud:
    stream:
      bindings:
        output:
          destination: msqueue
    
server:
  port: 8502
  
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8500/eureka/